### ISSUE TITLE
Latest published version on npm still depends on npm

### ISSUE THREAD

**Issue by rybesh** [yeun/open-color#108]
This was fixed long ago:

https://github.com/yeun/open-color/commit/2b9342d19133eb391828799aa85d686093e1f5ec#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

But the published package was never updated:

https://github.com/yeun/open-color/blob/v1.7.0/package.json

**Comment by rtivital** [comment]
@yeun do you need help on that? I guess things that needs to be done:

- Bump version in package.json – `"version": "1.7.0" -> "version": "1.7.1"`
- Publish new version to npm – `npm publish`

**Comment by sairion** [comment]
Sorry for make you guys wait for long time. I have published 1.8.0
