### ISSUE TITLE
NPM install SASS or LESS option

### ISSUE THREAD

**Issue by tanykim** [yeun/open-color#13]
Add a question to set which CSS complier is desired: SASS as a default option, LESS as an additional one. 

$ npm install open-color
Which compiler do you want to use?
1) SASS/SCSS (default)
2) LESS

**Comment by yeun** [comment]
@tanykim I can't fine how to add a question in npm install. Could you give me some link about that?

**Comment by tanykim** [comment]
I haven't built NPM package myself, but I'll look up. I think Bower has that option, maybe NPM doesn't have one though?

**Comment by eezing** [comment]
@tanykim NPM doesn't have the the option for prompting on install, which is probably a good idea considering one could potentially sit for hours answering prompts; when taking the entire dependency tree into account, any given project could contain hundreds or even thousands of installed packages.

Sticking with .scss is a good default. In terms of preprocessors, Sass is the most popular. If I were starting from scratch, I'd probably use vanilla .css. If you do ever decide to change, make sure you use "npm version major" as this would be a breaking change.

@yeun If you need help with npm deployments or have questions. Feel free to hit me up. Your color selection is great btw.

**Comment by yeun** [comment]
@tanykim I'll close this issue. If you find any way to do this, please reopen this issue.
