### ISSUE TITLE
open-color.json

### ISSUE THREAD

**Issue by syntagmatic** [yeun/open-color#18]
A JSON format would be convenient for JavaScript interfaces/visualizations. A file the D3 community frequently uses is colorbrewer.json which has a similar selection of palettes:

https://github.com/axismaps/colorbrewer/blob/master/export/colorbrewer.json

**Comment by yeun** [comment]
JSON format color scheme is added via #23
See https://github.com/yeun/open-color/blob/ed9732cae5b1ef047f2d41006d3433385c1bec9f/open-color.json
