### ISSUE TITLE
Script for change color hex at once

### ISSUE THREAD

**Issue by yeun** [yeun/open-color#23]
Script for change hex value in the list below.

- open-color.less
- open-color.scss
- open-color.css
- docs/_config.yml
- docs/_sass/_open-color.scss
- docs/download/open-color_*.*.*.aco
- docs/download/open-color_*.*.*.ase
- docs/download/open-color_*.*.*.sketchpalette

**Comment by eezing** [comment]
@yeun Yes, great idea! Do you have a method for this yet?

**Comment by eezing** [comment]
No worries, I submitted just for the record. Thanks!
