### ISSUE TITLE
Add exhaustive list of available colors

### ISSUE THREAD

**Issue by linterpreteur** [yeun/open-color#27]
Available colors, as of 29 September, are as following (sorted by alphabetical order):

> blue
cyan
grape
gray
green
indigo
lime
orange
pink
red
teal
violet
yellow

I think that would be more helpful if we can find the list on `README`.

**Comment by yeun** [comment]
That's a good idea! I'll add the list.

**Comment by yeun** [comment]
I added the list. But I did'n follow your suggestion about the sort. Because in this case, color name is just a name. "Grape" is could also be "purple" and it could have changed order. But the color spectrum is never change so I sort by that basis.
