### ISSUE TITLE
A preview of all the colors in the README.md

### ISSUE THREAD

**Issue by Larpon** [yeun/open-color#31]
... could maybe be an idea?

**Comment by makepanic** [comment]
I think it's only possible by generating an image that will be included in the README.
Github sanitizes html and removes styles that could be used to do this (`background-color`).

It would be kinda easy to use a svg template and add it to the template compiling step. The build svg could be included in the projects README.

@Larpon do only want a list of colors like this https://raw.githubusercontent.com/chriskempson/base16/master/logo.png or also having the colors name appear beside it?

@yeun if you want to do it like that, I could open a PR that does it.

**Comment by lukasoppermann** [comment]
That would be awesome. An image would probably be best in any case as it is easily updated when updating the colors.

Could you also add rgb codes into the image? This makes it easy to compare and use without including files, e.g. in sketch.

**Comment by yeun** [comment]
@makepanic Cool! I'd love to see it happen.

**Comment by Larpon** [comment]
@makepanic that was exactly what I had in mind. It would be a tremendous help for people just popping by to see what this is all about.

- a project about nice colors - but with no colors to see?
