### ISSUE TITLE
can you generator the colors for css style directly?

### ISSUE THREAD

**Issue by yeluolei** [yeun/open-color#35]
It will be very convenient to use if there is some css style generated directly including

background-color
color
border
fill
stroke

**Comment by makepanic** [comment]
could you elaborate on what you want to have?
Should there be a css file that contains classnames that enable open-color colors, background-colors, border-colors, fill, stroke, ...?

The problem i have with pregenerated classnames is that they could collide with existing project css conventions ([bem, oocss, ...](https://github.com/ikkou/awesome-css#architecture)).

**Comment by lukasoppermann** [comment]
Also you have css variables, why would you need classes like `border-lime-8`? This goes hugely against OOCSS best practises as you would have tons of classes on every element.

**Comment by yeluolei** [comment]
yes, you guys are right. I changed my build to scss, and there is no problem now~ thank you !
