### ISSUE TITLE
Live preview with copy & paste

### ISSUE THREAD

**Issue by lukasoppermann** [yeun/open-color#36]
Hey @yeun @makepanic,

I was just thinking an additional, very nice feature would be a live preview of the colors (html) with a copy functionality (user should be able to choose the format?).

Just like here: http://flatuicolors.com

For example I am currently using the colors as defaults for some web components. However, I am not loading the package into the components to keep it small. For this kind of workflow, or other design tools that do not have a palett to include, this would be very awesome addition to `/docs`.

**Comment by makepanic** [comment]
I'm not sure if @yeun wants to add this feature, but there are in general 2 ways of implementing it:

- maximum compatibility: http://zeroclipboard.org/ which is old and relies on flash but has a better [compatibility with older browsers](https://github.com/zeroclipboard/zeroclipboard#support)
- native browser api: [execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#Browser_compatibility) which [doesn't support older browser versions](http://caniuse.com/#feat=clipboard) (minimum Chrome 43, FF 41, IE9, Safari 10).

There's a lib that uses execCommand and falls back to an input where the user has to manually copy the selection: https://clipboardjs.com/#browser-support

**Comment by lukasoppermann** [comment]
Hey @makepanic I would think something like the last lib would be idea. Since it is just a nicety feature, I think requiring modern browser support for convenience features is fine. 👍

**Comment by yeun** [comment]
Sorry, I'd like to keep the UI simple as possible, not thinking of browser support / progressive enhancement / etc. If you want to discuss more, please reopen.
