### ISSUE TITLE
Printed Copy of Colours.

### ISSUE THREAD

**Issue by brianran** [yeun/open-color#37]
I like your open-colo schemer, but I cant seem to be able to print off any of the swatches even when I set printer to print background colours.
I will be using the SCSS file as a partial file importing to main style file.
I can,t print colours on any of the other program swatches which makes it difficult to choose without having swatches front of you.  Am I dealing with it in the right way, I am using RUBY  plus SASS and SUSY as a preprocessor, but placing scss file in SASS directory for import(Partial file)
Thank you Brianran

**Comment by makepanic** [comment]
alternatively you could print the colors svg: https://yeun.github.io/open-color/asset/images/open-color.svg

**Comment by makepanic** [comment]
you should be able to `@import path-to-open-color/open-color.scss` and use the open color sass variables in your styles.

example:
```
.mySelector{
  background-color: $oc-red-5:
}
```

**Comment by brianran** [comment]
Many thanks.
Although I am an experienced amateur see www.randallfamilyhistory.com we all have blips.
in my rush to check it out II omitted to point my html to style.css, 
Sorry!!

**Comment by yeun** [comment]
Thanks for your answer @makepanic.
