### ISSUE TITLE
Prettier Gimp pallette

### ISSUE THREAD

**Issue by m-e-h** [yeun/open-color#41]
Currently with `Columns: 0` [here](https://github.com/yeun/open-color/blob/master/templates/open-color.inkscape.hbs#L3) there is no organization of the palette.
![gimp0col](https://cloud.githubusercontent.com/assets/3585901/20039998/0e196cd6-a41d-11e6-90aa-fab60b19306e.png)

Assuming 0-9 for color variations, `Columns: 10` would produce an organized palette.
![gimp10col](https://cloud.githubusercontent.com/assets/3585901/20040010/55b1676a-a41d-11e6-9d30-aecacb777d57.png)
This also relies on https://github.com/yeun/open-color/pull/40

_This has no effect on Inkscape._

It also might make sense to rename this template to `open-color.gpl.hbs` to stay consistent with the other naming conventions. It's also used for several open source applications.

**Comment by yeun** [comment]
Merged
