### ISSUE TITLE
bower package

### ISSUE THREAD

**Issue by darlanmendonca** [yeun/open-color#43]
First congratulations for the project, is awesome !!

Just for convenience, has intention to add the project as a bower package?

**Comment by darlanmendonca** [comment]
the main files in bower.json can be a array, like

```json
main: [
  'open-color.scss',
  'open-color.styl',
  'open-color.less',
  'open-color.css',
]
```

this can be helpful to when use bower and automated ways to import and use dependencies into project

**Comment by kasiriveni** [comment]
@darlanmendonca i create a project and published the bower also if need more info look at repo https://github.com/kasiriveni/bower-open-color

Try bower install open-color

**Comment by darlanmendonca** [comment]
oh @kasiriveni nice!!

just for knowledge, dont be better the author @yeun register in bower instead fork and register like you do (I guess)?

I see the PR that you open, you add to readme the mention to bower package, but always the open-color is updated (the real repo), and release a new tag, you will need create a new tag too, in your custom repo, to release in bower?

**Comment by darlanmendonca** [comment]
I'm confuse about that :D

**Comment by kasiriveni** [comment]
@darlanmendonca  for  bower document there are mention like this
ex : bower register <my-package-name> <git-endpoint> so i follow 

bower register open-color https://github.com/yeun/open-color.git

i just create a package .json file and push it in my repo

i follow the angular bower concept https://github.com/angular/bower-angular


iam not sure is the right approach or not?

**Comment by darlanmendonca** [comment]
humm, so you register https://github.com/yeun/open-color.git like open-color in bower with 

```sh
bower register open-color https://github.com/yeun/open-color.git
```

the problem is, when I install it with ```bower install open-color``` the download of module run ok, but the module dont have a bower.json in your content, with main file defined

the original module https://github.com/yeun/open-color.git, need this file to allow use it 

in your PR https://github.com/yeun/open-color/pull/46, need be added the bower.json with main file defined to all works :D

**Comment by kasiriveni** [comment]
@darlanmendonca  i just update the PR https://github.com/yeun/open-color/pull/48
let me know if need any more changes :)

**Comment by darlanmendonca** [comment]
very nice!! now will works :D

@yeun looks this pls

**Comment by darlanmendonca** [comment]
I added the version to bower.json https://github.com/yeun/open-color/pull/49

and update the version to 1.4.1.

a new release is necessary to module can works for users when their install the module

in the current release (1.4.0), the bower.json dont exists, and sure, dont target to main file

**Comment by sairion** [comment]
It's up now - try `bower info open-color`

**Comment by darlanmendonca** [comment]
nice :D
