### ISSUE TITLE
CSS Variables + Current Browser Support

### ISSUE THREAD

**Issue by talbs** [yeun/open-color#45]
Hi, there! First of all, thanks so much for this awesome project. I've used it a few times already in personal and work projects. The scheme and extensibility is great!

Up until now I've only used the SCSS version of Open Color, but an upcoming project requires plain old CSS. Your current CSS version of Open Color leverages variables/custom properties which don't seem to be supported by all modern browsers yet (http://caniuse.com/#feat=css-variables). 

Am I missing something in the doc/src? Do you have a specific way that you implement the CSS version across browsers (e.g. polyfill)?

Thanks again for the great work and the help in advance.

**Comment by makepanic** [comment]
Afaik there is currently no way to polyfill CSS variables for unsupported browsers without a CSS processor.

You probably have to copy & paste the color values if you can't use an additional tool. 
We could try to implement https://github.com/yeun/open-color/issues/36 to make that use case easier. 
Do you think it would improve your situation?

**Comment by yeun** [comment]
@makepanic is right. If you have idea to improve this situation feel free to reopen to this issue.
