### ISSUE TITLE
Make color navigation sidebar follow scrolling

### ISSUE THREAD

**Issue by ElectricCookie** [yeun/open-color#47]
It would be nice if the sidebar on the left side followed when you scroll down, maybe even show a "back to top" at the bottom, since the length of the website varies depending on your aspect ratio.

**Comment by linterpreteur** [comment]
![css](http://imgur.com/qtpWh9A "css")

@yeun Setting `div.shortcut-wrap`'s `position` as `sticky` and specifying `top` for it would do the magic. "Back to top" button should be in `position: fixed`.

**Comment by yeun** [comment]
Position fixed navigation does not support low-height browsers, so I want to avoid them. But the back to top button is a good idea. Feel free to reopen this issue if you want to implement it.
