### ISSUE TITLE
Mac OS system color pallete

### ISSUE THREAD

**Issue by cezarmal** [yeun/open-color#52]
Hey there!
I create a open-color Mac OS pallete using [ColorTools](https://github.com/ramonpoca/ColorTools),
<img width="237" alt="captura de tela 2017-01-04 23 40 46" src="https://cloud.githubusercontent.com/assets/7670110/21666176/44af254a-d2d7-11e6-80a5-c8c2cdc4c9f9.png">

It was automatically generated using the .ase file provided.

This may be useful for someone. 😃 
[Download open-color_1.4.0.clr](https://github.com/yeun/open-color/files/686254/open-color_1.4.0.clr.zip)

**Comment by yeun** [comment]
Thanks! I added it to the download menu.
