### ISSUE TITLE
There is no TS definition file on npm registry

### ISSUE THREAD

**Issue by HyunSeob** [yeun/open-color#77]
Hi, I tried to use open-color with TypeScript, but something's wrong.
I have installed with yarn, and I just see that definition file has not installed.
As you know, there is [a definition file on GitHub repository](https://github.com/yeun/open-color/blob/master/open-color.d.ts). I guess the definition file has not published because you have published on npm registry without running [compile-templates.js](https://github.com/yeun/open-color/blob/master/compile-templates.js). (not sure) So, I propose setting the `prepublish` hook for making sure generating compiled files. As follow:

``` json
{
  "scripts": {
    "test": "npm run test-typescript",
    "test-typescript": "tsc open-color.d.ts tests/typescript.ts --noEmit",
    "compile-templates": "node compile-templates.js",
    "prepublish": "npm run compile-templates"
  }
}
```

If you want, I can make a PR.

Thank you!

**Comment by yeun** [comment]
Oh I understand. I would appreciate your work!
