### ISSUE TITLE
Website: Downloads > Source Code link broken

### ISSUE THREAD

**Issue by neumayr** [yeun/open-color#80]
Hey! @yeun 👋 

Just a short note, the link: `Downloads > Source Code` is broken.

<img width="258" alt="screen shot 2018-01-21 at 15 11 26" src="https://user-images.githubusercontent.com/13056188/35195020-75599e06-febd-11e7-9e0a-454df09a51e5.png">

**Comment by sairion** [comment]
Thanks! it's fixed now.
