### ISSUE TITLE
Feature: LaTeX colors

### ISSUE THREAD

**Issue by Pouya-moh** [yeun/open-color#83]
Hi.

For personal use, I created a latex scheme based on `open-color.css`. I can make a pull request if other are interested or it fits the purpose of the repo.

https://github.com/Pouya-moh/open-color/commit/a0be41e9e3a110634c48bd3e80f7a88502327287

**Comment by makepanic** [comment]
Great work!
I think it would be fine to add it to open-color.
If you want to, please try to create a template as described in [Adding new languages](https://github.com/yeun/open-color/blob/master/CONTRIBUTING.md#adding-new-languages)

**Comment by Pouya-moh** [comment]
Thanks! I did so and it seems to pass the CI test. But since I'm not familiar with Handlebars I don't know if generated `tex` file is okay...
