### ISSUE TITLE
Gravit Designer

### ISSUE THREAD

**Issue by thiagok** [yeun/open-color#87]
Hey guys! Thanks for this project!

I've been using Gravit Designer on Ubuntu because i'm without my mac and gravit has a another kind of palette that insn't in your project options. It's called `.gvswatch`.

Any plans for this extension?

**Comment by makepanic** [comment]
Do you know if there's a spec for gvswatch?
If not, can you maybe generate a sample file, so we can try to reverse engineer the format?

**Comment by thiagok** [comment]
Thanks guys!
