### ISSUE TITLE
Gaps between Gray 4-Gray 7.

### ISSUE THREAD

**Issue by mizuno-gsinet** [yeun/open-color#89]
I feel that the brightness of gray changes more rapidly between gray 4 and gray 7 than other colors, but I don't know how other people feel about it. Do you have any methods to quantify the perceived brightness?

**Comment by GiladFeder** [comment]
Agreed. The gap is somewhat too big.

**Comment by yeun** [comment]
Unlike other colors, gray has functions in the UI design, so the shade steps are not constant. I think [this post](https://yeun.github.io/open-color/gray-color.html) will explain, somehow why this difference occurs.
