### ISSUE TITLE
How to match with base/brand color?

### ISSUE THREAD

**Issue by dehghani-mehdi** [yeun/open-color#92]
Hi,

Really nice colors, I don't know if you generate them based on a color or not, but usually there is a brand/base color and rest of colors will be generated using that color. am I right? if so, how to match open color with a brand/base color?

Thanks.

**Comment by makepanic** [comment]
They're generated based on https://github.com/yeun/open-color/blob/master/open-color.json
which contains all individual colors. 

There is no color generation, only swatches and images are automatically generated based on that json definition.

**Comment by dehghani-mehdi** [comment]
I know there is no magic in this repo (in codes) and colors are pre-defined. I like to know how I can change color's properties (e.g: hue), to match all colors with specific base color

**Comment by fchristant** [comment]
@dehghani-mehdi The last chapter of this article perhaps answers your question:
https://ferdychristant.com/color-for-the-color-challenged-884c7aa04a56

**Comment by dehghani-mehdi** [comment]
@fchristant thank you for the link, I think you wrote that, nice job.
It wasn't the exact thing that I'm looking for though. I have one color (aka base or brand) and I want to change all other colors in Open Color based on that color. not to add another color to the palette .

**Comment by fchristant** [comment]
@dehghani-mehdi Thanks! Sorry, but that requirement makes no sense to me. What is the point of a color palette if they all have the same hue as a base color?

**Comment by dehghani-mehdi** [comment]
@fchristant I'm sorry, seems like I couldn't explain correctly, I don't want to change all color's hue to be a same as each other, I want to change their hue to be match with my base color. for example my brand color is `#ff1234`, using this color as base with Open Color is not correct (I think), so I want to alter Open Color to get the best result, based on my base color.

Or let me say this way, let's say there is no Open Color palette, I have a base color, so I need to find few other colors, red, green, yellow, orange, maybe some accent colors, gray colors. this color should be based on the base color (as much as possible) _I'm not designer of course, I just think it should be this way_. so now we have Open Color, let use it as base and try to alter the colors to get the best result.

**Comment by orangemooncreative** [comment]
@dehghani-mehdi why not pick a base color from open color and then use something like palx (https://palx.jxnblk.com/) to generate the rest of the palette? that is my typical workflow if i'm not using the entire palette from here.

**Comment by dehghani-mehdi** [comment]
@orangemooncreative the base/brand color is special and can not be picked from open color (in my opinion)

**Comment by orangemooncreative** [comment]
you could put your base/brand color in the tool i suggested instead. however it is not uncommon for brands to have a digital version of their brand colors. so if there was a color from open color that was close enough you probably could get away with it. assuming this is a new website/app if it is something inherited then see my first sentence :)

**Comment by dehghani-mehdi** [comment]
@orangemooncreative actually I found Open Color through Palx, I tried to generate the palette using Palx, it was good but not perfect for me, (_and I tried so many online and offline tools before posing this issue._)

**Comment by orangemooncreative** [comment]
ahhhhh. got it. i've found with color palettes there is no one size fits all. there is always tweaking necessary. i use a combination of open color, palx, colorable and 0to255 to build and refine my palettes. good luck!

**Comment by sairion** [comment]
While I think this discussion makes sense and worthy, unfortunately this project does not provide the magic something you would expect, so I will close this – It would be more of a graphic design problem.

There are tons of color scheme generators you can use (but personally I was never satisfied with them) e.g.) https://color.adobe.com/create
